#!/usr/bin/env bash

declare -A LOGGER_LEVEL_NAMES=([1]=error [2]=warn [3]=info [4]=debug [5]=trace)

LOGGER_FILE="${LOGGER_FILE:-/dev/null}";
LOGGER_LEVEL="${LOGGER_LEVEL:-3}";
LOGGER_TEMPLATE="${LOGGER_TEMPLATE:-}"

function logger_template()
{
    local COLOR_DARK_GRAY=""
    local COLOR_RESET=""

    if [ ! -f "$LOGGER_FILE" ] && tput colors &>/dev/null && [ "$(tput colors)" -ge 8 ]; then
        COLOR_DARK_GRAY='\x1b[90m'
        COLOR_RESET='\x1b[0m'
    fi

    echo "${COLOR_DARK_GRAY}%s[%s] %b${COLOR_RESET}\n";
}

function log ()
{
    local level="${1:-3}";
    test "$LOGGER_LEVEL" -ge "$level" || {
      true
      return;
    }

    [[ -z "${2:-}" ]] || {
        log "$1" <<< "$2";
        return
    };


    local timestamp;
    timestamp="$(logger_date)";

    touch "$LOGGER_FILE"

    local template="${LOGGER_TEMPLATE:-$(logger_template)}"

    xargs -l -r -d '\n' printf "$template" \
      "$timestamp" \
      "${LOGGER_LEVEL_NAMES[$level]}" |
      tee -a "$LOGGER_FILE" 1>&2
};

function logger_date ()
{
    date -Iseconds
};

function log_error() { log 1 "${1:-}"; }
function log_warn()  { log 2 "${1:-}"; }
function log_info()  { log 3 "${1:-}"; }
function log_debug() { log 4 "${1:-}"; }
function log_trace() { log 5 "${1:-}"; }
