#!/usr/bin/env bash

LOGGER_FILE="${LOGGER_FILE:-/dev/null}";
LOGGER_LEVEL="${LOGGER_LEVEL:-3}";
LOGGER_TEMPLATE="${LOGGER_TEMPLATE:-%s[%s] %b\n}";
LOGGER_SILENT="${LOGGER_SILENT:-}"

function log ()
{
    [[ -z "${2:-}" ]] || {
        log "$1" <<< "$2";
        return
    };
    local level="${1:-3}";
    local timestamp;
    timestamp="$(logger_date)";
    test "$LOGGER_LEVEL" -ge "$level" || return;
    xargs -l -r -d '\n' printf "$LOGGER_TEMPLATE" "$timestamp" "$level" | {
        if [[ -z "$LOGGER_SILENT" ]] ; then
            tee -a "$LOGGER_FILE" 1>&2
        else
            cat - > /dev/null
        fi
    }
};

function logger_date ()
{
    date -Iseconds
};

function logify ()
{
    "$@" 2> >(log 3)
};

function log_error() { log 1 "${1:-}"; }
function log_warn()  { log 2 "${1:-}"; }
function log_info()  { log 3 "${1:-}"; }
function log_debug() { log 4 "${1:-}"; }
function log_trace() { log 5 "${1:-}"; }
