#!/usr/bin/env bash

LOGGER_FILE="${LOGGER_FILE:-/dev/null}";
LOGGER_LEVEL="${LOGGER_LEVEL:-3}";
LOGGER_TEMPLATE="${LOGGER_TEMPLATE:-%s[%s] %b\n}";

function log ()
{
    [[ -z "${2:-}" ]] || {
        log "$1" <<< "$2";
        return
    };
    local level="${1:-3}";
    local timestamp;
    timestamp="$(date -Iseconds)";
    test "$LOGGER_LEVEL" -ge "$level" || return;
    xargs -r -d '\n' -l printf "$LOGGER_TEMPLATE" "$timestamp" "$level" | tee -a "$LOGGER_FILE" 1>&2
};

function logify ()
{
    eval "$@" 2> >(log 3)
}

function log_error() { log 1 "$1"; }
function log_warn()  { log 2 "$1"; }
function log_info()  { log 3 "$1"; }
function log_debug() { log 4 "$1"; }
function log_trace() { log 5 "$1"; }
